[package]
name = "binarchae-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.binarchae]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "engine_scan_memory"
path = "fuzz_targets/engine_scan_memory.rs"
test = false
doc = false
bench = false

[[bin]]
name = "handler_roundtrip"
path = "fuzz_targets/handler_roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "carving_rules"
path = "fuzz_targets/carving_rules.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1

[[bin]]
name = "archive_family"
path = "fuzz_targets/archive_family.rs"
test = false
doc = false
bench = false


[[bin]]
name = "filesystem_family"
path = "fuzz_targets/filesystem_family.rs"
test = false
doc = false
bench = false


[[bin]]
name = "registry_sqlite"
path = "fuzz_targets/registry_sqlite.rs"
test = false
doc = false
bench = false


[[bin]]
name = "network_family"
path = "fuzz_targets/network_family.rs"
test = false
doc = false
bench = false


[[bin]]
name = "memory_forensics_family"
path = "fuzz_targets/memory_forensics_family.rs"
test = false
doc = false
bench = false


[[bin]]
name = "firmware_family"
path = "fuzz_targets/firmware_family.rs"
test = false
doc = false
bench = false


[[bin]]
name = "document_family"
path = "fuzz_targets/document_family.rs"
test = false
doc = false
bench = false






